name: Warrant Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Go Env
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19.3"
      - name: Verify
        run: go mod verify
      - name: Build
        run: go build
